name: "codeql-extractor-bicep"
repository: "GitHubSecurityLab/codeql-extractor-bicep"
version: "0.2.1"

ecosystems:
  - Docs
  - GitHub
  - CodeQL

locations:
  - name: "GitHub Action"
    paths:
      - 'action.yml'
    patterns:
      - '{repo}@v?{version}'

  - name: "CodeQL Extractor"
    paths:
      - 'codeql-extractor.yml'
    patterns:
      - 'version:\s+{version}'
