name: "CodeQL Bicep Extractor"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "CodeQL Bicep Extractor"
        uses: ./ 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

